server:
  port: 8080

spring:
  application:
    name: gritten-service

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include:
          - "*"

greeting-service:
  greeting: "Olá"
  default-value: "Mundo"
